### ISSUE TITLE
Kicks when you click in your inventory 

### ISSUE THREAD

**Issue by HaydenRedhair** [Summiner/ServerPatches#10]
For some reason I guess some of the patches trying to fix out of bounds inventory clicking, it just kicks the player when they try to click in the inventory, i've disabled it for our server in the config.

**Comment by Summiner** [comment]
What version of the plugin are you using?

**Comment by HaydenRedhair** [comment]
Oh I just relized there’s a new version release, I was using the other release

**Comment by Summiner** [comment]
Seems to be resolved
