### ISSUE TITLE
ServerPatches causing Packet Events message to spam console!

### ISSUE THREAD

**Issue by ArcheryAce** [Summiner/ServerPatches#17]
![image](https://github.com/Summiner/ServerPatches/assets/74921968/47a5bc5a-7edf-46e7-b616-dcb7b40eb613)
This message is spammed to the console Constantly whenever ServerPatches is on the server! Including the Latest

According to Kichura from the ViaVersion community:
"this warning appears because it's trying to request for client version using old code method but won't work as it got superseded"

I'm not sure if this is the complete issue. Though it would be nice if this could be updated. I cant even read my console anymore due to the constant spam!

**Comment by Summiner** [comment]
Solved in the latest release, sorry for taking so long to reply
