### ISSUE TITLE
ServerPatches Kick

### ISSUE THREAD

**Issue by DuckyAurora** [Summiner/ServerPatches#6]
I had to disable some of the configs, because when you do Shift + Click on a Item it automatically kicks you from the server, so i had to disable all the Click Events from Config.

Also now i'm having a issue with CoreProtect ( Idk if this is related to the plugin ) But since i did put it on my server, it has started showing me SQLite Errors.

**Comment by Summiner** [comment]
Thank you for reporting the error with click events, I am now pushing a fix for this. I do not think the error from CoreProtect is related however if you can provide some of the error logs please do ^^

**Comment by Summiner** [comment]
This has now been resolved in the latest releases, thank you for reporting it <3
