### ISSUE TITLE
CONSOLE ERROR - 1.20.1 paper

### ISSUE THREAD

**Issue by misakburianek** [Summiner/ServerPatches#8]
Hello,

When I type /spatches into the console, I get an error, I'm using the version that was released two days ago, does this affect the plugin's functionality?

**Comment by misakburianek** [comment]
![image](https://github.com/Summiner/ServerPatches/assets/148539869/8d6ba54d-2032-4de8-adbb-06f083df4c4d)

**Comment by Summiner** [comment]
fixed in https://github.com/Summiner/ServerPatches/releases/tag/V1.0.3-release however this doesn't cause any actual issues with the plugin ^^
